#ifndef PINOUT_H_INCLUDED
#define PINOUT_H_INCLUDED

// PLL - MAX2871
#define CLK_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_0  //PA0
#define CLK_LOW GPIOA->BSRR|=GPIO_BSRR_BR_0   //PA0
#define DATA_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_7 //PB7
#define DATA_LOW GPIOB->BSRR|=GPIO_BSRR_BR_7  //PB7
#define LE_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_6   //PB6
#define LE_LOW GPIOB->BSRR|=GPIO_BSRR_BR_6    //PB6
#define RFEN_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_6 //PA6
#define RFEN_LOW GPIOA->BSRR|=GPIO_BSRR_BR_6  //PA6
#define MUX (GPIOA->IDR & GPIO_IDR_1) // PA1

// ATTEN - F1958
#define aCLK_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_5  //PA5
#define aCLK_LOW GPIOA->BSRR|=GPIO_BSRR_BR_5   //PA5
#define aMOSI_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_4 //PA4
#define aMOSI_LOW GPIOA->BSRR|=GPIO_BSRR_BR_4  //PA4
#define aLE_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_7   //PA7
#define aLE_LOW GPIOA->BSRR|=GPIO_BSRR_BR_7    //PA7

// MOD out
#define MOD_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_5  //PB5
#define MOD_LOW GPIOB->BSRR|=GPIO_BSRR_BR_5   //PB5

// Tipke
#define bUP (GPIOA->IDR & GPIO_IDR_9)
#define bLEFT (GPIOA->IDR & GPIO_IDR_11)
#define bRIGHT (GPIOA->IDR & GPIO_IDR_8)
#define bDOWN (GPIOA->IDR & GPIO_IDR_10)

// LCD
#define RS_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_0  //PB0
#define RS_LOW GPIOB->BSRR|=GPIO_BSRR_BR_0  //PB0
#define E_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_1  //PB1
#define E_LOW GPIOB->BSRR|=GPIO_BSRR_BR_1  //PB1
#define D4_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_12  //PA12
#define D4_LOW GPIOA->BSRR|=GPIO_BSRR_BR_12  //PA12
#define D5_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_15  //PA15
#define D5_LOW GPIOA->BSRR|=GPIO_BSRR_BR_15  //PA15
#define D6_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_3  //PB3
#define D6_LOW GPIOB->BSRR|=GPIO_BSRR_BR_3  //PB3
#define D7_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_4  //PB4
#define D7_LOW GPIOB->BSRR|=GPIO_BSRR_BR_4  //PB4


/* V1.0 - prototipna
// PLL - MAX2871
#define CLK_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_5  //PA5
#define CLK_LOW GPIOA->BSRR|=GPIO_BSRR_BR_5   //PA5
#define DATA_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_7 //PA7
#define DATA_LOW GPIOA->BSRR|=GPIO_BSRR_BR_7  //PA7
#define LE_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_4   //PA4
#define LE_LOW GPIOA->BSRR|=GPIO_BSRR_BR_4    //PA4
#define RFEN_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_4 //PB4
#define RFEN_LOW GPIOB->BSRR|=GPIO_BSRR_BR_4  //PB4
#define MUX (GPIOA->IDR & GPIO_IDR_6) // PA6

// ATTEN - F1958
#define aCLK_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_15  //PA15
#define aCLK_LOW GPIOA->BSRR|=GPIO_BSRR_BR_15   //PA15
#define aMOSI_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_3 //PB3
#define aMOSI_LOW GPIOB->BSRR|=GPIO_BSRR_BR_3  //PB3
#define aLE_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_0   //PA0
#define aLE_LOW GPIOA->BSRR|=GPIO_BSRR_BR_0    //PA0

// MOD out
#define MOD_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_5  //PB5
#define MOD_LOW GPIOB->BSRR|=GPIO_BSRR_BR_5   //PB5

// Tipke
#define bUP (GPIOA->IDR & GPIO_IDR_9)
#define bLEFT (GPIOA->IDR & GPIO_IDR_11)
#define bRIGHT (GPIOA->IDR & GPIO_IDR_8)
#define bDOWN (GPIOA->IDR & GPIO_IDR_10)

// LCD
#define RS_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_0  //PB0
#define RS_LOW GPIOB->BSRR|=GPIO_BSRR_BR_0  //PB0
#define E_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_1  //PB1
#define E_LOW GPIOB->BSRR|=GPIO_BSRR_BR_1  //PB1
#define D4_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_12  //PA12
#define D4_LOW GPIOA->BSRR|=GPIO_BSRR_BR_12  //PA12
#define D5_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_1  //PA1
#define D5_LOW GPIOA->BSRR|=GPIO_BSRR_BR_1  //PA1
#define D6_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_6  //PB6
#define D6_LOW GPIOB->BSRR|=GPIO_BSRR_BR_6  //PB6
#define D7_HIGH GPIOB->BSRR|=GPIO_BSRR_BS_7  //PB7
#define D7_LOW GPIOB->BSRR|=GPIO_BSRR_BR_7  //PB7
*/


#endif /* PINOUT_H_INCLUDED */
